import = [
	"~/.config/themes/themes/alabaster_dark.toml"
]

[font]
size=10

[font.normal]
family="iosevka"
style="regular"

[font.bold]
family="iosevka"
style="bold"

[font.italic]
family="iosevka"
style="oblique"

[font.bold_italic]
family="iosevka"
style="boldoblique"

[window]
opacity=0.95
